language: python

cache:
  directories:
    - $HOME/.cache/pip

matrix:
  include:
    - os: linux
      sudo: required
      python: 3.5
    - os: linux
      sudo: required
      python: 3.6
    - os: osx
      sudo: required
      language: generic

branches:
  only:
    - master
    - dev
    - osxtest

# solution based on https://gist.github.com/dan-blanchard/7045057
# setup anaconda to install scipy and numpy easily and quickly
before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh; else wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh; fi
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=$HOME/miniconda3/bin:$PATH
    - hash -r
    - conda update --yes conda
    - conda config --add channels r
    - conda config --add channels defaults
    - conda config --add channels conda-forge
    - conda config --add channels bioconda
    # are not specific to using mini
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo rm -rf /dev/shm; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo ln -s /run/shm /dev/shm; fi
    # This help testing code with pylab
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -e /etc/init.d/xvfb start; fi

install:
  - conda create --yes --name testenv python=$TRAVIS_PYTHON_VERSION
  - source activate testenv

  - conda install --yes --file requirements.txt
  - conda install --yes --file requirements_tools.txt
  - conda install --yes --file requirements_dev.txt
  - conda install --yes  coverage
  - pip install .
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then pip install pygatb --no-deps ; fi
  - pip install pypandoc
  - pip install biocode
  # bcftools 1.9.0 incompatible with samtools 1.9 due to differnt openssl
  # version. downgraded bcftools to 1.8
  - conda install --yes bcftools==1.8


# # command to run tests, e.g. python setup.py test
script:
  - pytest -v --durations=10  test/ --cov=bioconvert --cov-report term --timeout 300 -n 1


after_success:
  coveralls
