language: python

cache:
  directories:
    - $HOME/.cache/pip

matrix:
  include:
    - os: linux
      sudo: required
      python: 3.5
    - os: linux
      sudo: required
      python: 3.6
    - os: osx
      sudo: required
      language: generic

branches:
  only:
    - master
    - dev
    - osxtest

# solution based on https://gist.github.com/dan-blanchard/7045057
# setup anaconda to install scipy and numpy easily and quickly
before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh; else wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh; fi
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=$HOME/miniconda3/bin:$PATH
    - hash -r
    - conda update --yes conda
    - conda config --add channels r
    - conda config --add channels defaults
    - conda config --add channels conda-forge
    - conda config --add channels bioconda
    # are not specific to using mini
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo rm -rf /dev/shm; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo ln -s /run/shm /dev/shm; fi
    # This help testing code with pylab
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -e /etc/init.d/xvfb start; fi
    # some useful libraries to compile numpy/scipy
    # - "sudo apt-get install -q libatlas3gf-base libatlas-dev liblapack-dev gfortran"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - echo $TRAVIS_PYTHON_VERSION
  - conda install --yes python=$TRAVIS_PYTHON_VERSION --file requirements.txt
  - conda install --yes python=$TRAVIS_PYTHON_VERSION --file requirements_tools.txt
  - conda install --yes python=$TRAVIS_PYTHON_VERSION --file requirements_dev.txt
  - conda install --yes python=$TRAVIS_PYTHON_VERSION  coverage
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then pip install pygatb --no-deps ; fi
  - pip install pypandoc
  - pip install biocode


# # command to run tests, e.g. python setup.py test
script:
  - pytest -v --durations=10  test/ --cov=bioconvert --cov-report term --timeout 300 -n 1


after_success:
  coveralls
