name: bioconvert

channels:
- bioconda
- conda-forge
- defaults
- r

dependencies:
- python=3.7
- colorlog
- biopython
- numpy
- matplotlib
- pandas
- pyBigWig
- scipy
- pysam
- pillow
- easydev
- pip
- pyyaml
- pillow
- bedtools          # used in gallery and bam2bed
- singularity
- pigz
- dsrc
- sambamba
- bioawk
- seqtk
- seqkit
- graphviz   # provides dot for RTD
- icu

- pip:
  - docutils<0.13.1 # https://github.com/sphinx-doc/sphinx/issues/3212
  - pyexcel
  - pyexcel-ods3
  - pyexcel-xls

